name: sk58_printer
description: Flutter library for SK58 thermal printer via Bluetooth. Supports Android and Linux.
version: 0.1.0
homepage: https://github.com/mosu/sk58_printer
repository: https://github.com/mosu/sk58_printer

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_ble: ^1.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
